name: Compile LaTeX Document

on:
  push:
    branches:
      - main  # Adjust if your main branch has a different name
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex  # Replace with your actual LaTeX filename
          latexmk_use_xelatex: true  # Adjust if you prefer pdflatex or lualatex

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: main.pdf  # Ensure this matches the output filename

      - name: Deploy PDF to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: main.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
